### ISSUE TITLE
Job offer should use a range field for salary

### ISSUE THREAD

**Issue by rtio** [kdti/kdti-server#18]
Yes, we can improve that. I just started with bare minimum, we start with other cards. We can create a card for that.

Will we use a single value or a range like:

* 3500.49
Or:
* 2500.99 - 3000.05

_Originally posted by @ianrodrigues in https://github.com/kdti/kdti-server/pull/14_

**Comment by ianrodrigues** [comment]
I think for this first iteration we can stick to a simple value.

**Comment by carlosxjm** [comment]
I think that salary information can be composed by 2 fields, max and min value, both optional.
On the form it can be represented with two select with option following the pattern:
- Not inform;
- R$ 1.000,00;
- R$ 2.000,00;
- R$ 3.000,00;
- ...
- R$ 20.000,00 or more;

**Comment by ianrodrigues** [comment]
As per we talked today, the client will send two integers(floats?) from zero to ∞+.
